### ISSUE TITLE
Unable to install using github

### ISSUE THREAD

**Issue by JauntyJJS** [ProcessMiner/nlcor#3]
Hi, I tried to install this R package from source after reading the article https://towardsdatascience.com/estimating-non-linear-correlation-in-r-62c6571cb1db

Unfortunately, I have this error message.

```{r}
> library("devtools")
Loading required package: usethis
> install_github("ProcessMiner/nlcor")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 49/60
  Rate limit reset at: 2019-10-21 05:34:32 UTC
```

Is this error because of new updates in devtools ?

**Comment by cran2367** [comment]
Please try it again. An updated version is merged today.

**Comment by JauntyJJS** [comment]
Hi, I manage to install this package now. Thank you for your patience and help
